-- Step 1: Download DB
-- Step 2: Connect to database 
--     > mysql -u root -p
--     Enter password: ********
-- Step 3: Import using following command 
--     source path\mysqlsampledatabase.sql
-- Step 4: Verify
--     show databases;